### ISSUE TITLE
Conflict with Avatar: Out of the iceberg mod

### ISSUE THREAD

**Issue by BeardStroker** [JurassiCraftTeam/JurassiCraft2#413] opened 2018-08-20 03:38 UTC
JurassiCraft-1.12.2-2.1.16.jar
Forge 14.23.4.2765
Avatar 5.6

The last update somehow broke some jumping abilities from the Avatar mod. They work by selecting a ability and the next time you jump it activates, enhances the jump and removes fall damage. but after updating to the newest jurassicraft version the abilities will no longer activate after selecting them, it just stays primed and removes fall damage indefinitely. Removing jurassicraft solves the problem.

Any idea why and how to fix it? I took it up with the avatar developer and they said it's possible something is hindering packets from being sent properly but that's just a guess. Any help would be appreciated and I can provide any additional information that would be helpful.

**Comment by Mahtaran** [comment] 2018-08-21 17:29
@BeardStroker Is this also an issue when using 2.1.15?

**Comment by PT400C** [comment] 2018-08-21 20:35
It seems that this issue is caused by the Avatar mod. This should bei fixed by the next release of the Avatar mod.

**Closed by PT400C** 2018-08-21 20:35 UTC
Labels: 1.12.2, bug, incompatibility

**Comment by PT400C** [comment] 2018-08-22 20:05
@BeardStroker Meanwhile I highly suggest to change their helicopter's upward keybind to something other than SPACE (jump). That's a temporary fix for the problem until the Avatar mod releases the final bugfix.
