### ISSUE TITLE
Dinosaurs weird turn around

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#198] opened 2017-10-04 17:47 UTC
I think that this wasn't thoroughly explained; dinosaurs seem to rotate as if spinning in the air whenever they turn to look at another place. This happens with creatures like Triceratops, Parasaurolophus, Mussaurus, Gallimimus, goats, and presumably also with Tyrannosaurus, Velociraptor, Microraptor, and Dilophosaurus. It might happen with Coelacanth too.

**Comment by gegy1000** [comment] 2017-10-04 17:48
Duplicate of #196

**Closed** 2017-10-04 17:47 UTC
Labels: bug, duplicate

**Comment by epicslayer999** [comment] 2017-10-05 00:12
No! It's not a duplicate! D:
