### ISSUE TITLE
Sponge/Jurassicraft conflict

### ISSUE THREAD

**Issue by krisjenner** [JurassiCraftTeam/JurassiCraft2#561] opened 2019-03-27 19:25 UTC
jurassicraft needs to not writeToNbt to when calling getTileData

getTileData() in TourRailBlockEntity should NEVER be calling writeToNbt, otherwise this happens

https://github.com/JurassiCraftTeam/JurassiCraft2/blob/master-1.12.2/src/main/java/org/jurassicraft/server/block/entity/TourRailBlockEntity.java#L40

sponge uses getTileData() because forge mods should be using that to store extra information, not to write to that tag

JurassiCraft-1.12.2-2.1.21
Sponge 7.1.0

I hope this helps

**Comment by PT400C** [comment] 2019-03-28 11:11
@krisjenner What is the actual problem? A crash? Serious lag?

**Comment by krisjenner** [comment] 2019-03-28 14:16
Sorry. Yes it causes a complete server crash when placing tracks

**Comment by PT400C** [comment] 2019-03-29 10:26
@krisjenner Alright, thank you for your submission. Just for me to investigate this on a root-level: Please send the version of Sponge and a full log which contains the crash.

**Comment by Shrek5InTheatres2019** [comment] 2019-03-30 04:25
no this is fully expected. Spongeforge is very broken and has no documentation. I don't recommend using it until it's actually good enough to not break every mod it touches

**Comment by gabizou** [comment] 2019-04-16 15:39
To give some insight from Sponge's side of things:

Forge added the `customTileData` field a while back as an easy way for mods to attach whatever data to that compound without needing to worry about overriding or injecting into vanilla/other mods `TileEntity#write/read` methods, as mentioned in the original PR: https://github.com/MinecraftForge/MinecraftForge/pull/1755.

Because of this legacy age old contract, Sponge abides by it by using the compound to store Sponge specific data (really all it does is add some extra data for tracking which player placed which block/tile entity, etc.) and to do that, it piggybacks on the `getTileData()` method, as referenced in the [`IMixinTileEntity`](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/interfaces/block/tile/IMixinTileEntity.java#L45-L65). So, because Forge's method is a lazy initializing method, we wrote it with the mindset that it wouldn't be recursively called for writing to nbt, as your [TourBlockEntity#getTileData()](https://github.com/JurassiCraftTeam/JurassiCraft2/blob/master-1.12.2/src/main/java/org/jurassicraft/server/block/entity/TourRailBlockEntity.java#L40) overrides to do.

For some references of the type of recursive nature this brings about, there were some reports with a rare few other mods in the past: [from way back in 2017](https://gist.github.com/gabizou/0e0475ab6345fb3f679f760278bf3e93), but the jurassicraft one, I can't seem to recall where the log was posted, but the issue is the very same in nature.




> no this is fully expected. Spongeforge is very broken and has no documentation. I don't recommend using it until it's actually good enough to not break every mod it touches

Don't be toxic. Sponge has plenty of documentation and it very much doesn't break every mod it touches.

**Comment by krisjenner** [comment] 2019-04-17 13:15
> no this is fully expected. Spongeforge is very broken and has no documentation. I don't recommend using it until it's actually good enough to not break every mod it touches

I'll do one better and not use JurassiCraft until it's actually good enough to not break Sponge

**Comment by PT400C** [comment] 2019-05-30 19:22
Should be resolved by the next update.

**Closed by PT400C** 2019-05-30 19:22 UTC
Labels: 1.12.2, crash, incompatibility, missing logs, needs verification
