### ISSUE TITLE
Dinosaurs ticks 

### ISSUE THREAD

**Issue by iLefty** [JurassiCraftTeam/JurassiCraft2#148] opened 2017-07-10 06:24 UTC
Your dinosaurs is very laggy, they have a lot of ticks, that decrease server TPS. Look at timings:
https://timings.aikar.co/?id=bc0b5c1ac50b4425aaaaf5bbc8a0d47f
https://timings.aikar.co/?id=4b2a5033f8d849f8b7250e061a92932b

I hope, dinos have ticks, when they hungry.

**Comment by twoninefour** [comment] 2017-07-10 06:40
The biggest time difference I can see between the T-Rex/dilo and the other dinos is the large number of targetTasks they have registered. I'm going to do some testing to see if streamlining the targetTasks to do fewer nearby entity queries has any impact.

**Comment by gegy1000** [comment] 2017-07-10 06:55
At the lowest level, this goes down to path finding, which is quite intensive, especially for bigger entities such as the tyrannosaurus, which has a bigger collision box. I'd imagine the targeting AI does path checks for each entity it targets, so that would probably be useful.

**Comment by gegy1000** [comment] 2017-07-10 06:56
Also, this is a duplicate of #127. Continue this there.

**Closed by gegy1000** 2017-07-10 06:56 UTC
