### ISSUE TITLE
Tyrannosaurus Sleeping Animation Bug

### ISSUE THREAD

**Issue by TheCarrotJet** [JurassiCraftTeam/JurassiCraft2#521] opened 2019-01-10 07:34 UTC
Tyrannosaurus tries to sleep, and begins playing the animation, getting up, then playing the animation, etc. As it is doing this, it makes a loud "crunching" sound, and the overlays stay in place and detach from the main body.
![2019-01-09_22 52 59](https://user-images.githubusercontent.com/38549509/50953063-236c5500-1467-11e9-9d1d-58771c429923.png)
![2019-01-09_22 53 00](https://user-images.githubusercontent.com/38549509/50953064-236c5500-1467-11e9-9a62-0d17609bf75b.png)
![2019-01-09_22 53 17](https://user-images.githubusercontent.com/38549509/50953065-236c5500-1467-11e9-8679-35587ad65d44.png)
![2019-01-09_22 53 27](https://user-images.githubusercontent.com/38549509/50953066-236c5500-1467-11e9-99be-cb2249c71003.png)
![2019-01-09_22 53 29](https://user-images.githubusercontent.com/38549509/50953067-236c5500-1467-11e9-80aa-0561cead611d.png)
![2019-01-09_22 53 30](https://user-images.githubusercontent.com/38549509/50953068-236c5500-1467-11e9-926e-6e1e59aa8641.png)

**Comment by GarchompGirl** [comment] 2019-01-28 00:48
that is terrifying

**Comment by PT400C** [comment] 2019-01-28 13:17
@GarchompGirl Indeed. Did you experience it as well?

**Comment by GarchompGirl** [comment] 2019-01-29 04:49
No I haven't.

**Comment by PT400C** [comment] 2019-05-29 14:40
@TheCarrotJet I really can't reproduce that. *Closing this here until it happens again ;)*

**Closed by PT400C** 2019-05-29 14:40 UTC
Labels: 1.12.2, bug, severe
