### ISSUE TITLE
Action figures - Gender not applied on serverside

### ISSUE THREAD

**Issue by StarWarsDinosaur** [JurassiCraftTeam/JurassiCraft2#425] opened 2018-08-27 22:03 UTC
On servers when you place female brachiosaurus they are just male.

**Comment by CraftedMods** [comment] 2018-08-28 15:17
I can confirm this. Clientside the action figures work as expected, but as soon as I use a separate server, the gender property seems to be ignored. I also reproduced that for other action figures. Probably the error lies at the networking code. I'll take a look at it.

**Comment by PT400C** [comment] 2018-08-31 17:10
This will be fixed with a further release. Here's the [link](https://github.com/JurassiCraftTeam/JurassiCraft2/pull/426) to the fix for quick reference.

**Closed by PT400C** 2018-08-31 17:10 UTC
Labels: 1.12.2, bug, server-side
