### ISSUE TITLE
Mob Tick Lag (maybe brachiosaurus)

### ISSUE THREAD

**Issue by chrislightsaber** [JurassiCraftTeam/JurassiCraft2#174] opened 2017-07-27 02:44 UTC
so i have encountered an issue that has plagued me for quite a while, On my jurassicraft 2.05 1.11.2 world sometimes mobs (the dinosaurs) lag. i believe this is due to the brontosaurs. Whenever i have a 20+ group of dinosaurs randomly mixed, there is no lag. but as soon as 5+ brachiosaurs are thrown in and you wait a minute, the dinosaurs start to lag. Any way to solve

**Comment by chrislightsaber** [comment] 2017-07-27 03:09
Also if i keep the brachiosaurs far away by themselves i can have more than five without lag (with no dinosaurs near)

**Comment by chrislightsaber** [comment] 2017-07-27 03:12
actuially in further testing, i have 10+ brachiosaurs and 5 dilophosaurs without lag... yet at my other island where theres around 50 dinosaurs mixed there is lag that seems to be brachiosaur related????? HELP

**Comment by gegy1000** [comment] 2017-08-07 16:49
Duplicate of #127

**Closed by gegy1000** 2017-08-07 16:49 UTC
