### ISSUE TITLE
Raptors stuck in attack mode

### ISSUE THREAD

**Issue by DragonSpirit653** [JurassiCraftTeam/JurassiCraft2#574] opened 2019-05-23 14:49 UTC
My velociraptors are or seem to be stuck in attack mode and I don't know why. I put my world in peaceful mode and they are still in that position. Any idea as to why that is? [ Edit ] And it keeps them from sleeping.

**Comment by PT400C** [comment] 2019-05-30 18:40
Marked as duplicate of #575

**Closed by PT400C** 2019-05-30 18:40 UTC
Labels: invalid
