### ISSUE TITLE
T-Rex Crash

### ISSUE THREAD

**Issue by jredfox** [JurassiCraftTeam/JurassiCraft2#449] opened 2018-09-12 05:21 UTC
Crash Side Server Not Dedicated: https://pastebin.com/4dXJgkrP

**Comment by PT400C** [comment] 2018-09-12 08:08
Thank you for that report! That's caused by something one of our developers seems to have removed from the code. It will be fixed with the next release.

**Closed by PT400C** 2018-09-12 08:08 UTC
Labels: 1.12.2, crash
