### ISSUE TITLE
Infinite AI loop, crashes the server due to overload

### ISSUE THREAD

**Issue by terrybougard** [JurassiCraftTeam/JurassiCraft2#557] opened 2019-02-25 05:54 UTC
After killing some dinosaurs, then the server became so lag its like something keeps computing in an infinite loop, then it crashes. Even after I restart the server, the problem stays.
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 2/24/19 3:48 PM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at org.jurassicraft.server.entity.ai.util.OnionTraverser$OnionIterator.next(OnionTraverser.java:64)
	at org.jurassicraft.server.entity.ai.util.OnionTraverser$OnionIterator.next(OnionTraverser.java:31)
	at org.jurassicraft.server.entity.ai.metabolism.DrinkEntityAI.func_75250_a(DrinkEntityAI.java:39)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1168)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at org.jurassicraft.server.entity.ai.util.OnionTraverser$OnionIterator.next(OnionTraverser.java:64)
	at org.jurassicraft.server.entity.ai.util.OnionTraverser$OnionIterator.next(OnionTraverser.java:31)
	at org.jurassicraft.server.entity.ai.metabolism.DrinkEntityAI.func_75250_a(DrinkEntityAI.java:39)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1168)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)

-- Thread Dump --
Details:
	Threads: "pool-3-thread-1" Id=156 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4465f2c3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4465f2c3
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


"pool-6-thread-1" Id=153 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4aa2043f
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4aa2043f
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"pool-10-thread-1" Id=151 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4e9d99b3
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4e9d99b3
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"pool-9-thread-1" Id=148 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@b9f0e04
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@b9f0e04
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"pool-7-thread-1" Id=146 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6007065e
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6007065e
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"Chunk I/O Executor Thread-1" Id=145 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3a5e659d
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3a5e659d
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


"Netty Epoll Server IO #2" Id=144 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)


"threadDeathWatcher-2-1" Id=143 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)


"Netty Epoll Server IO #1" Id=142 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)


"Server Watchdog" Id=58 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:45)
	at java.lang.Thread.run(Thread.java:748)


"RCON Listener #1" Id=57 RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at net.minecraft.network.rcon.RConThreadMain.run(SourceFile:69)
	at java.lang.Thread.run(Thread.java:748)


"File IO Thread" Id=56 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51)
	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
	at java.lang.Thread.run(Thread.java:748)


"Timer-0" Id=55 TIMED_WAITING on java.util.TaskQueue@182c3364
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@182c3364
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)


"Netty Epoll Server IO #0" Id=54 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)


"Thread-8" Id=50 RUNNABLE (in native)
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.superzanti.serversync.ServerSetup.run(ServerSetup.java:175)
	at java.lang.Thread.run(Thread.java:748)


"Java2D Disposer" Id=41 WAITING on java.lang.ref.ReferenceQueue$Lock@6bb0f14b
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@6bb0f14b
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:748)


"JLine terminal non blocking reader thread" Id=23 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at org.jline.utils.InputStreamReader.read(InputStreamReader.java:270)
	-  locked java.io.FileInputStream@335d3f95
	at org.jline.utils.InputStreamReader.read(InputStreamReader.java:200)
	-  locked java.io.FileInputStream@335d3f95
	at org.jline.utils.NonBlockingReader.run(NonBlockingReader.java:276)
	at java.lang.Thread.run(Thread.java:748)


"Server console handler" Id=22 TIMED_WAITING on org.jline.utils.NonBlockingReader@7ae6d6ee
	at java.lang.Object.wait(Native Method)
	-  waiting on org.jline.utils.NonBlockingReader@7ae6d6ee
	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:174)
	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:113)
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:132)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:109)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:60)
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:724)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:526)
	...


"DestroyJavaVM" Id=21 RUNNABLE


"Server thread" Id=19 RUNNABLE
	at org.jurassicraft.server.entity.ai.util.OnionTraverser$OnionIterator.next(OnionTraverser.java:64)
	at org.jurassicraft.server.entity.ai.util.OnionTraverser$OnionIterator.next(OnionTraverser.java:31)
	at org.jurassicraft.server.entity.ai.metabolism.DrinkEntityAI.func_75250_a(DrinkEntityAI.java:39)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1168)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	...


"Server Infinisleeper" Id=18 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:82)


"Snooper Timer" Id=17 TIMED_WAITING on java.util.TaskQueue@3287dc5
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@3287dc5
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)


"Signal Dispatcher" Id=4 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@6ffeee42
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@6ffeee42
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@3505c5bf
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@3505c5bf
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)



Stacktrace:
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:62)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-45-generic
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3205466664 bytes (3056 MB) / 6022496256 bytes (5743 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 2 total; -Xmx16384M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2807 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version              | Source                                            | Signature                                |
	|:------ |:------------------------- |:-------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2               | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                       | 9.42                 | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                       | 8.0.99.99            | forge-1.12.2-14.23.5.2807-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                     | 14.23.5.2807         | forge-1.12.2-14.23.5.2807-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | dsurroundcore             | 3.5.4.3              | minecraft.jar                                     | None                                     |
	| LCHIJA | amd                       | 1.12.2-0.0.1.2       | amd-1.12.2-0.0.1.2.jar                            | None                                     |
	| LCHIJA | biomesoplenty             | 7.0.1.2419           | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar     | None                                     |
	| LCHIJA | craftstudioapi            | 1.0.0                | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
	| LCHIJA | twilightforest            | 3.8.689              | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| LCHIJA | animania                  | 1.6.2                | animania-1.12.2-1.6.2.jar                         | None                                     |
	| LCHIJA | as                        | 0.1.4                | as-0.1.6.jar                                      | None                                     |
	| LCHIJA | authmod                   | 2.6                  | authmod-2.6.jar                                   | None                                     |
	| LCHIJA | bullseye                  | 3.0.7                | Bullseye-1.12.2-3.0.7.jar                         | None                                     |
	| LCHIJA | chameleon                 | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHIJA | coralreef                 | 2.0                  | CoralReef-2.5-1.12.2.jar                          | None                                     |
	| LCHIJA | customnpcs                | 1.12                 | CustomNPCs_1.12.2(26aug18).jar                    | None                                     |
	| LCHIJA | props                     | 2.6.2                | Decocraft-2.6.2_1.12.2.jar                        | None                                     |
	| LCHIJA | enhancedvisuals           | 1.0                  | EnhancedVisuals_v1.2.1_mc1.12.2.jar               | None                                     |
	| LCHIJA | familiarfauna             | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
	| LCHIJA | foamflower                | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar               | None                                     |
	| LCHIJA | jei                       | 4.13.1.225           | jei_1.12.2-4.13.1.225.jar                         | None                                     |
	| LCHIJA | ftblib                    | 5.4.1.77             | FTBLib-5.4.1.77.jar                               | None                                     |
	| LCHIJA | ftbutilities              | 5.3.0.75             | FTBUtilities-5.3.0.75.jar                         | None                                     |
	| LCHIJA | gravestone                | 1.10.1               | gravestone-1.10.1.jar                             | None                                     |
	| LCHIJA | journeymap                | 1.12.2-5.5.3         | journeymap-1.12.2-5.5.3.jar                       | None                                     |
	| LCHIJA | jaff                      | 1.7_for_1.12         | JustAFewFish-1.7_for_1.12.jar                     | None                                     |
	| LCHIJA | locks                     | 2.2.1                | Locks-2.2.1.jar                                   | None                                     |
	| LCHIJA | malisiscore               | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| LCHIJA | malisisdoors              | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCHIJA | millenaire                | MillÃ©naire 7.1.2     | millenaire-1.12.2-7.1.2.jar                       | None                                     |
	| LCHIJA | moreplayermodels          | 1.12.2               | MorePlayerModels_1.12.2(18jan18).jar              | None                                     |
	| LCHIJA | morpheus                  | 1.12-3.3.2           | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| LCHIJA | recipehandler             | 0.12                 | NoMoreRecipeConflict-0.12(1.12.2).jar             | None                                     |
	| LCHIJA | roguelike                 | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LCHIJA | ruins                     | 17.1                 | Ruins-1.12.2.jar                                  | None                                     |
	| LCHIJA | sereneseasons             | 1.2.15               | SereneSeasons-1.12.2-1.2.15-universal.jar         | None                                     |
	| LCHIJA | com.superzanti.serversync | 2.6.17               | serversync-2.6.17.jar                             | None                                     |
	| LCHIJA | simulatednights           | 1.12-2.1.0           | simulatednights-1.12-2.1.0.jar                    | None                                     |
	| LCHIJA | spartanshields            | 1.4.1                | SpartanShields-1.12.2-1.4.1.jar                   | None                                     |
	| LCHIJA | storagedrawers            | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
	| LCHIJA | toughasnails              | 3.1.0.139            | ToughAsNails-1.12.2-3.1.0.139-universal.jar       | None                                     |
	| LCHIJA | treechopper               | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                      | None                                     |
	| LCHIJA | variedcommodities         | 1.12.2               | VariedCommodities_1.12.2(15may18.jar              | None                                     |
	| LCHIJA | vending                   | 1.12.2-3.0.1.2       | vending-1.12.2-3.0.1.2.jar                        | None                                     |
	| LCHIJA | waystones                 | 4.0.67               | Waystones_1.12.2-4.0.67.jar                       | None                                     |
	| LCHIJA | wearablebackpacks         | 3.1.3                | WearableBackpacks-1.12.2-3.1.3.jar                | None                                     |
	| LCHIJA | worldedit                 | 6.1.10-SNAPSHOT      | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | orelib                    | 3.5.2.2              | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                 | 3.5.4.3              | DynamicSurroundings-1.12.2-3.5.4.3.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | llibrary                  | 1.7.17               | llibrary-1.7.17-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | jurassicraft              | 2.1.21               | JurassiCraft-1.12.2-2.1.21.jar                    | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 50; [EntityPlayerMP['ArmyLeader'/489, l='world', x=951.72, y=67.00, z=-2698.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by PT400C** [comment] 2019-02-25 06:00
@terrybougard Hey, which type of dinosaur causes the issue and are really all dinosaurs dead? Also, could you send the world of the server? That would really help.

**Comment by terrybougard** [comment] 2019-02-25 09:59
I'm sorry I already removed the mod to make the world working. But for the dino its corythosaurus if im correct... the head which has a comb.

**Comment by terrybougard** [comment] 2019-02-25 10:01
some of them spawned in the forest get stuck half body on the ground... or stucked at the trees.

**Comment by PT400C** [comment] 2019-02-26 15:50
1. Replication of the issue was possible

**Comment by terrybougard** [comment] 2019-03-02 01:52
Please do message back when its fixed. I am eager to put jurassicraft back to my world. thanks!

**Comment by GarchompGirl** [comment] 2019-03-02 05:32
Seems like it is caused by some dinosaur in your world drinking water.

**Comment by PT400C** [comment] 2019-03-02 06:54
So, exactly. We were able to reproduce the glitch, but it's scheduled so far. Here are my tips for avoiding it: 1. Don't build your dino pen underground 2. Don't build it below the sea level. 3. Don't build it directly above the sea.
That should cause your world to crash not anymore. 
Good luck at figuring out the best way to avoid the crash for now :)

**Comment by terrybougard** [comment] 2019-03-03 16:06
but, I config them to spawn in the world... it will definitely crash at some time...

**Comment by PT400C** [comment] 2019-03-03 16:07
Okay, then I can't help you right now. Maybe deactivate the automated spawning for now?

**Comment by terrybougard** [comment] 2019-03-03 17:17
its alright, I'll wait for the update for the fix. my world is for exploration. its so nice to see dinos in the world.

**Comment by Canus8** [comment] 2019-04-11 13:31
I can confirm that this does not only apply to natural spawn brachiosaurus, but to naturally spawning raptors and player-placed brachiosaurus (but only when they reach juvenile age).  I also am just using single player.

**Comment by PT400C** [comment] 2019-05-29 14:41
#421 This is referenced to this issue.

**Comment by PT400C** [comment] 2019-06-01 11:38
@terrybougard @Canus8 @GarchompGirl This should be fixed by the next JC release 👍

**Comment by terrybougard** [comment] 2019-06-20 19:16
Wow! I'm excited for the next release!

**Closed** 2019-06-30 13:51 UTC
Labels: 1.12.2, ai, bug, crash, severe
