### ISSUE TITLE
Tidbits and suggestions + bugs.

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#209] opened 2017-10-08 19:35 UTC
- [x] ~~/animate does NOT work for me. It doesn't seem to detect the entities.~~

- [x] ~~Gallimimus seem to be able to leap 2 blocks. They should only be able to leap 2 blocks if they're flocking or running.~~

- [x] Brachiosaurus don't seem to eat from Araucaria trees, even though the trees seem to be at level with their head.

- [x] ~~Dinosaurs can see you through low security electric fence wires. But the carnivores still try to get entities. Maybe the dinosaurs should be able to tell that they CAN'T catch the entity on the other side of the wire, especially if it's tall enough to stop them and active.~~

- [ ] Action figures seem to be different sizes. I feel like they should all be the same size to be more consistent.

- [x] ~~Mussaurus don't seem to flee from carnivores when they're on their own.~~

- [x] ~~Please re-add the sleeping behavior for Coelacanth. It was amazing having something be nocturnal.~~

- [x] Microraptor don't seem to be able to get to the top of a tree when it has leaves.

- [x] ~~Gallimimus and Parasaurolophus may have their legs de-attached when using leg articulation. Larger sizes of these two should have articulation, because those larger ones don't lose their limbs. Smaller ones shouldn't articulate. Hope this is possible.~~

- [ ] Dinosaurs seem to turn around weirdly. Instead of their neck looking over at something and then the body following, the whole body rotates at once. You can see it perfectly in the JurassiCraft Sunday Teaser #3, towards the point in time when Cody spawns Velociraptors to show their jumping A.I. When a Velociraptor turns to stare at the distance, that's what I'm talking about. https://www.youtube.com/watch?v=XEFy31G4lxA

**Comment by gegy1000** [comment] 2017-10-08 19:45
1. You're ordering the arguments wrong.
2. Addressed in #207 
4. This is intentional.
5. Noted.
6. If this is happening, it's global among all dinosaurs
7. We will most likely not.
8. Cannot reproduce
9. The articulation is scaled already, this shouldn't be possible.

**Closed** 2018-06-12 01:03 UTC
Labels: ai, bug, suggestion
