### ISSUE TITLE
Paddock signs do not place on multiplayer servers

### ISSUE THREAD

**Issue by Cazsius** [JurassiCraftTeam/JurassiCraft2#385] opened 2018-08-12 06:02 UTC
The Paddock Signs are 100% functional on singleplayer. This could be due to a syncing issue or it could be lag, I'm not entirely sure.

**Comment by CraftedMods** [comment] 2018-08-12 12:38
I cannot reproduce that issue. Tested it locally in the development environment, based on `1.12.2-master`. I also looked at the code: The GUI for the paddock signs is opened server-side, a packet sent to the client,opening the GUI. Then, when the sign was selected, a packet is sent back to the server, where then the sign will be created, and the client will be informed about that with at least another packet. So even if the GUI is open, at least two packets have to travel that a sign can spawn, so I guess that lag can be the cause for that issue. At which multiplayer server did you test it? Could you test it again?

**Comment by PT400C** [comment] 2018-08-12 12:42
@CraftedMods We tested it on the official JC server: mc.jurassicraftmod.com. For me - from Germany - with low latencies the issue didn't happen too. Caz probably experienced a high latency while testing it. 
Btw, do you have a Discord account? It would be great, to exchange information without having to create a new comment on issues all the time.

**Comment by CraftedMods** [comment] 2018-08-12 12:45
Yes, Malvegil#1928. But dor documentation purposes, it's good if at least keypoints of an issue and of the cause and solution are posted here, for the case that something similar occurs later.

**Comment by Cazsius** [comment] 2018-08-12 18:55
When you right-click a block you select the creature in the GUI and it disappears. I assume this is a latency issue -  For Clarification.

**Comment by CraftedMods** [comment] 2018-08-15 15:09
Can this be closed?

**Comment by PT400C** [comment] 2018-08-15 15:38
We still need further information why and then this happens. As you're not able to reproduce this, it doesn't mean that the issue doesn't exist. When Caz has some time, he'll probably test that again and provide required data we need to reproduce this problem.

**Comment by CraftedMods** [comment] 2018-08-15 15:59
For me it seems like something that simply can't be fixed. But do like you think.

**Comment by PT400C** [comment] 2018-09-30 13:00
That's directly related to the official server and it's claim plugin. The flag "entity-spawn" also prevents JC from summoning the paddock signs.

**Comment by PT400C** [comment] 2018-10-07 06:33
As GriefPrevention stops certain entities from spawning, one needs to allow it to spawn. Here's the command: `/cf entity-spawn jurassicraft:paddocksign true override`

**Closed by PT400C** 2018-10-07 06:33 UTC
Labels: 1.12.2, bug, official server, server-side
