### ISSUE TITLE
Server crash when Veliciraptor attack other dinosaur

### ISSUE THREAD

**Issue by djdanby** [JurassiCraftTeam/JurassiCraft2#452] opened 2018-09-13 16:22 UTC
Is an complete new created server. Forge 2705

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 9/13/18 6:10 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:124)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:698)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:962)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:124)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:698)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:962)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft:entities.velociraptor (org.jurassicraft.server.entity.dinosaur.VelociraptorEntity)
	Entity ID: 16984
	Entity Name: Velociraptor
	Entity's Exact location: 374.82, 64.00, -199.02
	Entity's Block location: World: (374,64,-200), Chunk: (at 6,4,8 in 23,-13; contains blocks 368,0,-208 to 383,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.18, -0.08, 0.20
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['DjDanby'/191, l='world', x=361.47, y=68.74, z=-194.04]]
	Chunk stats: ServerChunkCache: 718 Drop: 0
	Level seed: -849276279148511375
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-140,64,256), Chunk: (at 4,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 33920 game time, 33920 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 5140 (now: true), thunder time: 30582 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.17-1-pve
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 781610392 bytes (745 MB) / 2306867200 bytes (2200 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xmx4096M -Xms512M -XX:MaxPermSize=256m
	IntCache: cache: 7, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                        | Version      | Source                                  | Signature                                |
	|:--------- |:------------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                 | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                       | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                       | 8.0.99.99    | forge-1.12.2-14.23.4.2705-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                     | 14.23.4.2705 | forge-1.12.2-14.23.4.2705-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ptrmodellib               | 1.0.2        | Decocraft PTRLib-1.0.2.jar              | None                                     |
	| UCHIJAAAA | props                     | 2.6.1        | Decocraft-2.6.1_1.12.2.jar              | None                                     |
	| UCHIJAAAA | excp                      | 1.0.3b       | extraCreepers-1.0.3b.jar                | None                                     |
	| UCHIJAAAA | com.superzanti.serversync | 2.6.17       | serversync-2.6.17.jar                   | None                                     |
	| UCHIJAAAA | llibrary                  | 1.7.15       | Jurassicraft llibrary-1.7.15-1.12.2.jar | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | jurassicraft              | 2.1.17       | JurassiCraft-1.12.2-2.1.17.jar          | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['DjDanby'/191, l='world', x=361.47, y=68.74, z=-194.04]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by PT400C** [comment] 2018-09-13 19:06
Thank you for reporting that bug! As it's a duplicate of another issue here #420

**Closed by PT400C** 2018-09-13 19:06 UTC
