### ISSUE TITLE
Dilophosaurus are cannibals?!

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#123] opened 2017-01-23 04:06 UTC
Now, before you ask me if they were at maximum limit, my Park had 5 Dilophosaurs. So, this happened when one of my friends who was to care for the Dilos didn't feed them cause he was somehow unlucky enough to go to their Paddock at the times when they were awake. So, they were starving and somehow killed each other. If this is a feature about Dilos eating themselves after there is nothing else to eat it's really cool. Lel.

**Comment by gegy1000** [comment] 2017-01-29 15:09
Could this not be caused by the server entity duplication glitch?

**Comment by crakiMDH** [comment] 2017-04-17 19:36
Sorry for replying so late, but I counted 5 Dilophosaurus when I witnessed them killing each other.

**Comment by gegy1000** [comment] 2017-07-15 06:14
They may have accidentally hit a fellow dilophosaurus instead of their instead of their target when spitting?

**Comment by crakiMDH** [comment] 2017-08-01 13:41
No, there wasn't anything for them to attack but themselves.

**Comment by gegy1000** [comment] 2017-10-02 13:31
Can't reproduce, closing for now.

**Closed by gegy1000** 2017-10-02 13:31 UTC
Labels: ai, bug
