### ISSUE TITLE
Dinosaurs seem to get confuzzled.

### ISSUE THREAD

**Issue by epicslayer999** [JurassiCraftTeam/JurassiCraft2#206] opened 2017-10-08 19:19 UTC
Sometimes dinosaurs just stay in a loop where they travel back and forth just randomly. Mostly seems to happen to Dilophosaurus and Velociraptor. Witnessed once or twice with Mussaurus.

**Comment by SanAndreasP** [comment] 2018-02-17 21:23
can't reproduce it, it may have been fixed with recent AI improvements.

**Closed by SanAndreasP** 2018-02-17 21:23 UTC
Labels: ai, bug
